version: "3.1"

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "6033:3306"
    environment:
      - MYSQL_DATABASE=management
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
